### ISSUE TITLE
Video post not visible until clicking 

### ISSUE THREAD

**Issue by GeEnrique** [h-unterp/fiduc-bugs#10]
Post with video is blank until clicking on the post. Image 1 is how it appears before clicking, image 2 shows video appears after clicking. 
![5BC8E01E-803B-40D7-AB22-05A8CE45EE66](https://user-images.githubusercontent.com/118128591/202070617-d0f93690-ebaa-4d83-8f05-185e88d1cab8.png)
![290A861C-4A1B-4431-9CDA-A20420E5F603](https://user-images.githubusercontent.com/118128591/202070619-e99d21ae-2a84-4a8e-9a64-47bcf3de8fe3.png)

**Comment by h-unterp** [comment]
I'm aware. This will be half-fixed in the next version. Thank you!

**Comment by GeEnrique** [comment]
Gotcha! Awesome to see you signing btw

**Comment by h-unterp** [comment]
Purple play button is the solution for now, in v15.
