### ISSUE TITLE
Notifications vanishing on refresh 

### ISSUE THREAD

**Issue by GeEnrique** [h-unterp/fiduc-bugs#11]
Notifications vanishing from menu on refresh 

https://user-images.githubusercontent.com/118128591/202071438-e3f6fe2d-e955-46e0-b8de-7c2433bc2cc1.MOV

**Comment by h-unterp** [comment]
Can you please confirm the app version you are seeing this in? And can you force quit app and confirm you are still seeing this? Thank you

**Comment by GeEnrique** [comment]
This was in v.14, but looks to be resolved in .16!
