### ISSUE TITLE
0.0.14

### ISSUE THREAD

**Issue by bcrace18** [h-unterp/fiduc-bugs#12]
**Describe the bug**
I was unable to load a profile of myself. A gray screen appeared.

**To Reproduce**
I clicked on "home", then "edit profile" then got the gray screen with "exception: face not recognized. Please try again."

**Expected behavior**
To upload the profile photo that I put in my first "fid."

**Screen Recordings and Screenshots**
![IMG_9035](https://user-images.githubusercontent.com/118379182/202239056-e5c8c745-6c40-441e-bc9c-7d36fc30d83c.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - iOS 15.4.1
 - Fiducia Version 0.0.14

**Additional context**
That's it for now.

**Comment by h-unterp** [comment]
same as: https://github.com/h-unterp/fiduc-bugs/issues/8.

I've uploaded your image, so you run into this again.
