### ISSUE TITLE
GIF issue for 0.0.16

### ISSUE THREAD

**Issue by mtcontreras18** [h-unterp/fiduc-bugs#13]
**Describe the bug**
GIF does not work when uploaded. 

**To Reproduce**
1. Go to profie
2. Click on photo
3. Choose GIF

**Expected behavior**
The GIF should have movement, instead it behaves like a photo

**Screen Recordings and Screenshots**

https://user-images.githubusercontent.com/117555340/202550118-81170e32-a5d7-4ff8-826d-51eb99d48f0f.mov

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 15.6.1
 - Fiducia Version 0.0.16

**Comment by h-unterp** [comment]
Fixed in v22 (will come out tomorrow, currently testflight having issues)
