### ISSUE TITLE
0.0.16 GIF motion problem

### ISSUE THREAD

**Issue by bcrace18** [h-unterp/fiduc-bugs#14]
**Describe the bug**
I uploaded a GIF but it had no motion. 

**To Reproduce**
1. Go to the upload
2. Click on gif
3. post gif
4. gif is static

**Expected behavior**
the gif should move like a film

**Screen Recordings and Screenshots**
![IMG_9038](https://user-images.githubusercontent.com/118379182/202617727-d6adba36-1f63-40ef-aab9-54c5123d605f.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: 15.4.1
 - Fiducia Version 0.0.16

**Comment by h-unterp** [comment]
Noted. Thank you

**Comment by h-unterp** [comment]
Duplicate of https://github.com/h-unterp/fiduc-bugs/issues/14

**Comment by h-unterp** [comment]
duplicate of https://github.com/h-unterp/fiduc-bugs/issues/13
