### ISSUE TITLE
Post are not populating in order on home page 

### ISSUE THREAD

**Issue by mtcontreras18** [h-unterp/fiduc-bugs#16]
**Describe the bug**
When I make a post, it does not post in order on my personal page.

**To Reproduce**
1. Go to home page
2. Click on "feather" to post
3. Write post
4. Ends up in the middle of the page

**Expected behavior**
A post should go to the top of ones own personal page, not end up in the middle.

**Screen Recordings and Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: 15.6.1
 - Fiducia Version. 0.0.17

**Additional context**

**Comment by h-unterp** [comment]
verified. investigating

**Comment by h-unterp** [comment]
fixed in v18
