### ISSUE TITLE
Hashtags not being found

### ISSUE THREAD

**Issue by mtcontreras18** [h-unterp/fiduc-bugs#17]
**Describe the bug**
When introducing a hashtag like # FidSocial you should be able to find all other related hashtags

**To Reproduce**
1. Go to "feather" to post
2. add a hashtag
3. post
4. click hashtag to find other similar hashtags -- none are found even with their being multiple hashtags

**Expected behavior**
you should be able to see all of the same hashtags 

**Screen Recordings and Screenshots**

https://user-images.githubusercontent.com/117555340/202781634-55c4a58d-c0e0-4d02-b62a-543aced92da9.mov

**Smartphone (please complete the following information):**
  - Device: iPhone 11
 - OS: 15.6.1
 - Fiducia Version. 0.0.17

**Additional context**

**Comment by h-unterp** [comment]
Some of the earlier hashtags won't work because I was making a change. But any hashtags you create new will work, I just confirmed.
