### ISSUE TITLE
Changing the "feather quill" 

### ISSUE THREAD

**Issue by mtcontreras18** [h-unterp/fiduc-bugs#18]
**Is your feature request related to a problem? Please describe.**
To post on Fidsocial we have a feather quill - which is a feature on twitter

**Describe the solution you'd like**
Just a different icon for writing instead of the quill that twitter is known for. 

**Describe alternatives you've considered**
If we want to be original it should be our 'fid' horn or narwal horn to write with.

**Additional context**
<img width="142" alt="Screen Shot 2022-11-18 at 3 21 52 PM" src="https://user-images.githubusercontent.com/117555340/202795536-38ab541d-e942-4aea-90b5-56bd3ee01e58.png">
this twitter quill. Ours is similar. We should change that.

**Comment by h-unterp** [comment]
![image](https://user-images.githubusercontent.com/772917/202850222-f727ca09-1ccf-4744-9ccf-59c2a62a31a7.jpeg)

**Comment by h-unterp** [comment]
Twitter has a + see image above
