### ISSUE TITLE
Homepage grays out 5minutes after posting a Fid

### ISSUE THREAD

**Issue by Empressjanine** [h-unterp/fiduc-bugs#20]
Describe the bug
The homepage grays out after posting a Fid.

To Reproduce
1. Go to the homepage of the “Fid” app.
2. Click on the feather icon found below on the right.
3. Click on the screen to bring up phone keyboard.
4. Type a message .
5. Click the picture icon to add a picture below to your written message .
6. Click the “Fid” icon on the top right of the page.
7. The post successfully loads.
8. Reload the page after 5minutes

Actual behavior 
The page grays out 5 minutes after posting a Fid

**Expected behavior**
The posted message should display on the screen continuously along side new posts.

**Screen Recordings and Screenshots**
Screen recordings help us out the most and if you can reproduce the issue in a video and add it here, that would be amazing! 

**Smartphone (please complete the following information):**
 - Device: [Iphone 14]
 - OS: [ios 16.0.3]
 - Fiducia Version (0.1.2)

**Additional context**
The circle on the right below should indicate a call to action for any other Add ons the user would like to add to the post

**Comment by h-unterp** [comment]
I believe I fixed this issue. The username and name on signup was erroring, causing users to be created with impartial data.

I fixed the bug and then manually edited your username and name. Feel free to ask me to change it to whatever you want, as currently there is no way to edit those values in the profile.

Also make sure to follow me by searching for hunter in the search tab, I have followed you. Thank you
