### ISSUE TITLE
Video attachment disappears upon clicking the Fid icon

### ISSUE THREAD

**Issue by Empressjanine** [h-unterp/fiduc-bugs#22]
**Describe the bug**
After a successful video attachment, the video disappears upon clicking the Fid button.

**To Reproduce**
1. User should have a video in Google photos 
2. Go to the Fid app homepage.
3. Click on click on the ‘feather’ sign found on the bottom right .
4. Click on the image icon on the bottom left to select a video  from Google photos 
5. Click on ‘Confirm’ to upload the video.

**Expected behavior**
The video Should upload successfully in real time on the app after clicking the Fid button.

**Screen Recordings and Screenshots**
Find attachment below 

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: IOS 16.0.3
 - Fiducia Version 0.1.2

**Additional context**

**Comment by h-unterp** [comment]
The only photo/video upload supported is from your phone's local gallery not from any cloud service like Google Photos. 

Pretty sure this is a feature request, however it is very low priority. Unless I have missed something?

**Comment by Empressjanine** [comment]
- Actually the video is from my local gallery.
- Please can you see my attached video on the bug report?

**Comment by h-unterp** [comment]
There is no attached video to this report, can you please upload again? Thank you

**Comment by Empressjanine** [comment]
@h-unterp 

File 51mb and unable to upload here. can I send  via email?

**Comment by h-unterp** [comment]
Sure, thank you

**Comment by h-unterp** [comment]
Should be fixed.
