### ISSUE TITLE
User is unable to edit profile successfully 

### ISSUE THREAD

**Issue by Empressjanine** [h-unterp/fiduc-bugs#23]
**Describe the bug**
The ‘Edit profile’ grays out after the button is clicked on.

**To Reproduce**
1. User should be signed into the app.
2. Click on the menu button found on top left of the homepage.
3. Click on “Profile”
4. click on “Edit profile”

**Expected behavior**
The user should be able to successfully upload up picture on the profile.

**Screen Recordings and Screenshots.
Find attached video below.

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 16.0.3.
 - Fiducia Version 0.1.2.

https://user-images.githubusercontent.com/93427231/208271885-b7598fc4-3aa4-4a1b-8915-7fc4dca3584f.MOV

**Comment by h-unterp** [comment]
Fixed
