### ISSUE TITLE
picture doesn’t update after clicking save

### ISSUE THREAD

**Issue by Empressjanine** [h-unterp/fiduc-bugs#24]
**Describe the bug**
The profile image doesn’t update after clicking the save icon.

**To Reproduce**
1. Go to the Fid homepage.
2. Click on the menu button on the top right of the homepage.
3. Click on “Profile” 
4. Click on Edit profile.
5. Click on the image icon to bring up the “pick an image” 
6. Choose to take a picture using the camera option or choose a picture from phone local gallery 
7. Click the save button on the top right of the page .

**Expected behavior**
Picture should update successfully after clicking save button.

**Screen Recordings and Screenshots**
Screen recordings help us out the most and if you can reproduce the issue in a video and add it here, that would be amazing! 

**Smartphone (please complete the following information):**
 - Device: [iPhone14]
 - OS: [e.g. iOS 16.0.3]
 - Fiducia Version (0.1.3)

Will attach a video to your email, unable to upload here.

**Comment by h-unterp** [comment]
Good catch, but currently, the profile image saves after uploading it. This is more of a UX enhancement than a bug. Closing. Thank you

**Comment by Empressjanine** [comment]
Good morning, I tried saving a profile picture but it still didn’t save . Is the profile picture not meant to update after clicking the save button?
