### ISSUE TITLE
Page  posts does not display in a chronological order 

### ISSUE THREAD

**Issue by Empressjanine** [h-unterp/fiduc-bugs#25]
**Describe the bug**
The user posts doesn’t display in a chronological order. Some new post displayed below while older posts appeared at the top.

**To Reproduce**
1. Go to homepage 
2. Click on the feather sign 
3. Click on the image icon to upload a photo or video and confirm.
4. Reload the homepage.

**Expected behavior**
The post should appear in order from newest to oldest.

**Screen Recordings and Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Iphone 14]
 - OS: [iOS 16.0.3]
 - Fiducia Version (0.1.3)

**Additional context**

**Comment by Empressjanine** [comment]
[Link to the video show the bug](https://share.icloud.com/photos/086DkDDw4gcbXj5mCA--4wzzA)

**Comment by h-unterp** [comment]
I tried to reproduce this but cannot.

**Comment by Empressjanine** [comment]
[Link to the video ](https://share.icloud.com/photos/0d7pbw6JoicE2POJCSUwCzD6Q) 

-Good morning,  attached here is Another video showing the actual result.

- Repost a post on the homepage
