### ISSUE TITLE
The menu option on the profile page is not consistent across user accounts 

### ISSUE THREAD

**Issue by Empressjanine** [h-unterp/fiduc-bugs#26]
**Describe the bug**
The menu options on the profile page of the user is different on different user accounts.

**To Reproduce**
1. Go to Fid homepage 
2. Click on the menu option on the top left of the page.
3. Click the profile icon 
4. Click the hamburger menu on the top right of the page.

**Expected behavior**
The menu should display the same information consistently across accounts.

**Screen Recordings and Screenshots**
![3072A1E3-AD6C-4C88-BEC6-4167FCE2EF6F](https://user-images.githubusercontent.com/93427231/209074307-c8924d0a-93a3-4d33-a2ae-8634b98ce1e8.png)
![7D28BCF4-29CB-4FBA-9F48-BDE342E65FF7](https://user-images.githubusercontent.com/93427231/209074323-18da8971-e5f7-49b5-ad07-2cbe04cfb188.png)

**Smartphone (please complete the following information):**
 - Device: [Iphone 14]
 - OS: [IOS 16.0.3]
 - Fiducia Version (0.1.3)

**Comment by h-unterp** [comment]
fixed
