### ISSUE TITLE
Credit Balance icon is not clickable 

### ISSUE THREAD

**Issue by Empressjanine** [h-unterp/fiduc-bugs#28]
**Describe the bug**
The “Credit balance” is not clickable and is grayed out.
**To Reproduce**
1. Go to 'Fid ‘app 
2. Navigate to the menu button on the   top left of the homepage.
3. Click on the “Credit Balance” icon on the Profile page.

**Expected behavior**
The Credit balance should be clickable and be displayed to view .

**Screen Recordings and Screenshots
![82915A10-EF63-4E3E-A5E4-4DE9C21EE817](https://user-images.githubusercontent.com/93427231/209417940-37dc8472-7fc8-4e71-a1f5-12fdc227a9ea.png)

**Smartphone (please complete the following information):**
 - Device: [IPHONE 14]
 - OS: [IOS 16.0.3]
 - Fiducia Version (0.1.3)

**Additional context**
-Are the balance linked to the product or services provided on the app ? 
- Will there a payment options linked in the app?

**Comment by h-unterp** [comment]
This is not a feature.
