### ISSUE TITLE
Notification icon  doesn’t display content

### ISSUE THREAD

**Issue by Empressjanine** [h-unterp/fiduc-bugs#31]
**Describe the bug**
The notification icon indicates messages but  does not display content when clicked .

**To Reproduce**
1. On the homepage of Fid app 
2. Click on the feather like icon on the right of the page 
3. Upload a photo or write a thought 
4. Click on the “Fid” icon found on the top right corner of the page.
5. Refresh the homepage by clicking on the screen
6. The notification icon will have a message 
7. Click the notification icon to view message.

**Expected behavior**
The notification should indicate any updates or changes made on the users timeline 

https://user-images.githubusercontent.com/93427231/216754655-6e97076a-11f8-4d6d-82cd-e4d9c5ccf090.MOV

**Smartphone (please complete the following information):**
 - Device: IPhone 14
 - OS: IOS 16.0.3
 - Fiducia Version (0.3.7)

**Comment by h-unterp** [comment]
cannot reproduce
