### ISSUE TITLE
Notifications disappearing in tab

### ISSUE THREAD

**Issue by GeEnrique** [h-unterp/fiduc-bugs#9]
Notification icon shows new notification briefly before disappearing, notification tab shows new notifications and after refreshing most disappear. 
![CF934DD4-C522-47DE-AB31-465597E76F33](https://user-images.githubusercontent.com/118128591/201745724-79477e6e-3160-48a8-a0f3-fcad1a6936d8.png)
![C565A3A0-CAB6-4607-BFA5-B96A85C78898](https://user-images.githubusercontent.com/118128591/201745728-80d38781-bcd4-4820-82d8-27eeb809bc2e.png)

**Comment by h-unterp** [comment]
Confirmed, investigating. Thank you

**Comment by h-unterp** [comment]
Fixed in v14
